language: go

go:
  - "1.11"

services:
  - docker

install:
  - sudo apt-get remove postgresql-* -y
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-client-11

before_script:
  - cp sqlboiler.toml.ci sqlboiler.toml
  - cp .env.ci .env
  - docker-compose up -d pg
#   - timeout 30 docker-compose exec pg bash -c "until psql -c '\q' -U postgres; do sleep 0.5; done"
  - sleep 10
  - scripts/setup-db -y
  - scripts/setup-test-db -y
  - go get -v -u github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only

script:
  - go test -v -race ./...

notifications:
  email:
    on_success: never
    on_failure: always
