language: go

go:
  - "1.11"

services:
  - docker
  - postgresql

install:
  - scripts/setup-ci

script:
  - go test -v -race ./...

notifications:
  email:
    on_success: never
    on_failure: always
