version: "3"

services:
  accounts:
    image: programminglab/prolab-accounts:latest
    restart: always
    volumes:
      - ./sqlboiler.toml:/sqlboiler.toml
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "${ACCOUNTS_DB_PASSWORD}"
      MYSQL_DATABASE: "accounts"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0.11-alpine
    hostname: redis
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local
