// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	AchievementUsers       string
	Achievements           string
	Blogs                  string
	Departments            string
	EmailConfirmations     string
	Entries                string
	GithubContributionDays string
	Invitations            string
	PasswordResets         string
	Profiles               string
	Roles                  string
	Users                  string
}{
	AchievementUsers:       "achievement_users",
	Achievements:           "achievements",
	Blogs:                  "blogs",
	Departments:            "departments",
	EmailConfirmations:     "email_confirmations",
	Entries:                "entries",
	GithubContributionDays: "github_contribution_days",
	Invitations:            "invitations",
	PasswordResets:         "password_resets",
	Profiles:               "profiles",
	Roles:                  "roles",
	Users:                  "users",
}
