version: "3"

services:
  ridgepole:
    build: .
    volumes:
      - .:/db
    environment:
      - DATABASE_URL=${DATABASE_URL_RIDGEPOLE}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL_RIDGEPOLE}
    network_mode: "host"
