#!/bin/sh

docker-compose -f db/docker-compose.yml up -d
if [ $? -gt 0 ]; then
    exit
fi

docker-compose -f db/docker-compose.yml exec ridgepole sh -c "bundle install -j2 && ridgepole --version"
if [ $? -gt 0 ]; then
    exit
fi

docker-compose -f db/docker-compose.yml exec ridgepole ridgepole -c env:DATABASE_URL --apply --dry-run
if [ $? -gt 0 ]; then
    exit
fi

while true; do
    read -p 'Are you sure you want to apply changes? [Y/n]' ans
    case $ans in
        [Y] ) break;;
        [Nn] ) exit;;
        * ) echo "Input [Y/n]";;
    esac
done

docker-compose -f db/docker-compose.yml exec ridgepole ridgepole -c env:DATABASE_URL --apply
