#!/bin/sh

docker-compose -f db/docker-compose.yml run --rm --entrypoint "ridgepole -c env:DATABASE_URL --apply --dry-run" ridgepole
if [ $? -gt 0 ]; then
    exit
fi

while true; do
    read -p 'Are you sure you want to apply changes? [Y/n]' ans
    case $ans in
        [Y] ) break;;
        [Nn] ) exit;;
        * ) echo "Input [Y/n]";;
    esac
done

docker-compose -f db/docker-compose.yml run --rm --entrypoint "ridgepole -c env:DATABASE_URL --apply" ridgepole
