#!/bin/sh

go get -v -u github.com/golang/dep/cmd/dep
dep ensure -v -vendor-only

cp sqlboiler.toml.ci sqlboiler.toml
cp .env.ci .env
psql -c 'create database accounts;' -U postgres
scripts/setup-db -y
