// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contribution_conllections.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContributionConllection struct {
	User                 *User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	TotalCount           int32              `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Days                 []*ContributionDay `protobuf:"bytes,3,rep,name=days,proto3" json:"days,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContributionConllection) Reset()         { *m = ContributionConllection{} }
func (m *ContributionConllection) String() string { return proto.CompactTextString(m) }
func (*ContributionConllection) ProtoMessage()    {}
func (*ContributionConllection) Descriptor() ([]byte, []int) {
	return fileDescriptor_c00b0a8aeb03b5ac, []int{0}
}
func (m *ContributionConllection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContributionConllection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContributionConllection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContributionConllection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributionConllection.Merge(m, src)
}
func (m *ContributionConllection) XXX_Size() int {
	return m.Size()
}
func (m *ContributionConllection) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributionConllection.DiscardUnknown(m)
}

var xxx_messageInfo_ContributionConllection proto.InternalMessageInfo

func (m *ContributionConllection) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ContributionConllection) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ContributionConllection) GetDays() []*ContributionDay {
	if m != nil {
		return m.Days
	}
	return nil
}

type ContributionDay struct {
	Date                 *types.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContributionDay) Reset()         { *m = ContributionDay{} }
func (m *ContributionDay) String() string { return proto.CompactTextString(m) }
func (*ContributionDay) ProtoMessage()    {}
func (*ContributionDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_c00b0a8aeb03b5ac, []int{1}
}
func (m *ContributionDay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContributionDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContributionDay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContributionDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributionDay.Merge(m, src)
}
func (m *ContributionDay) XXX_Size() int {
	return m.Size()
}
func (m *ContributionDay) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributionDay.DiscardUnknown(m)
}

var xxx_messageInfo_ContributionDay proto.InternalMessageInfo

func (m *ContributionDay) GetDate() *types.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ContributionDay) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListContributionConllectionsRequest struct {
	UsersCount           int32    `protobuf:"varint,1,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContributionConllectionsRequest) Reset()         { *m = ListContributionConllectionsRequest{} }
func (m *ListContributionConllectionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContributionConllectionsRequest) ProtoMessage()    {}
func (*ListContributionConllectionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c00b0a8aeb03b5ac, []int{2}
}
func (m *ListContributionConllectionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListContributionConllectionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListContributionConllectionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListContributionConllectionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContributionConllectionsRequest.Merge(m, src)
}
func (m *ListContributionConllectionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListContributionConllectionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContributionConllectionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContributionConllectionsRequest proto.InternalMessageInfo

func (m *ListContributionConllectionsRequest) GetUsersCount() int32 {
	if m != nil {
		return m.UsersCount
	}
	return 0
}

type ListContributionConllectionsResponse struct {
	ContributionConllections []*ContributionConllection `protobuf:"bytes,1,rep,name=contribution_conllections,json=contributionConllections,proto3" json:"contribution_conllections,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *ListContributionConllectionsResponse) Reset()         { *m = ListContributionConllectionsResponse{} }
func (m *ListContributionConllectionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContributionConllectionsResponse) ProtoMessage()    {}
func (*ListContributionConllectionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c00b0a8aeb03b5ac, []int{3}
}
func (m *ListContributionConllectionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListContributionConllectionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListContributionConllectionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListContributionConllectionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContributionConllectionsResponse.Merge(m, src)
}
func (m *ListContributionConllectionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListContributionConllectionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContributionConllectionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContributionConllectionsResponse proto.InternalMessageInfo

func (m *ListContributionConllectionsResponse) GetContributionConllections() []*ContributionConllection {
	if m != nil {
		return m.ContributionConllections
	}
	return nil
}

func init() {
	proto.RegisterType((*ContributionConllection)(nil), "programming_lab.prolab_accounts.ContributionConllection")
	proto.RegisterType((*ContributionDay)(nil), "programming_lab.prolab_accounts.ContributionDay")
	proto.RegisterType((*ListContributionConllectionsRequest)(nil), "programming_lab.prolab_accounts.ListContributionConllectionsRequest")
	proto.RegisterType((*ListContributionConllectionsResponse)(nil), "programming_lab.prolab_accounts.ListContributionConllectionsResponse")
}

func init() { proto.RegisterFile("contribution_conllections.proto", fileDescriptor_c00b0a8aeb03b5ac) }

var fileDescriptor_c00b0a8aeb03b5ac = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x8a, 0xd4, 0x40,
	0x14, 0xa5, 0x66, 0xa6, 0x5d, 0x54, 0x23, 0x6a, 0x21, 0x18, 0x63, 0xd3, 0x69, 0xa2, 0x42, 0x6f,
	0x3a, 0x91, 0x56, 0x44, 0x71, 0xd7, 0xdd, 0xee, 0x66, 0x21, 0x51, 0x11, 0xdd, 0x84, 0x4a, 0xa6,
	0x8c, 0x85, 0x49, 0x7e, 0xac, 0xfa, 0x99, 0xa1, 0xb7, 0x5e, 0xc1, 0xb5, 0x27, 0xf1, 0x02, 0xee,
	0x14, 0x3c, 0x80, 0xd2, 0x78, 0x02, 0x2f, 0xa0, 0xa4, 0x92, 0x38, 0x61, 0x20, 0xdd, 0xca, 0x64,
	0x95, 0xfa, 0xef, 0xff, 0xf7, 0xdf, 0x7b, 0x54, 0x51, 0x27, 0x86, 0x1c, 0x95, 0x8c, 0x4a, 0x94,
	0x90, 0x87, 0x31, 0xe4, 0x69, 0x2a, 0xe2, 0xea, 0x5f, 0x7b, 0x85, 0x02, 0x04, 0xe6, 0x14, 0x0a,
	0x12, 0xc5, 0xb3, 0x4c, 0xe6, 0x49, 0x98, 0xf2, 0xa8, 0x2a, 0xa7, 0x3c, 0x0a, 0x79, 0x1c, 0x43,
	0x99, 0xa3, 0xb6, 0xef, 0x27, 0x12, 0xdf, 0x94, 0x91, 0x17, 0x43, 0xe6, 0x67, 0x27, 0x12, 0xdf,
	0xc2, 0x89, 0x9f, 0xc0, 0xcc, 0x4c, 0xcf, 0x8e, 0x79, 0x2a, 0x8f, 0x38, 0x82, 0xd2, 0xfe, 0xdf,
	0xdf, 0x9a, 0xd8, 0x1e, 0x25, 0x00, 0x49, 0x2a, 0x7c, 0x5e, 0x48, 0x9f, 0xe7, 0x39, 0x20, 0xef,
	0xac, 0xb5, 0x6f, 0x34, 0xa8, 0x39, 0x45, 0xe5, 0x6b, 0x5f, 0x64, 0x05, 0xae, 0x1b, 0xd0, 0x39,
	0x0b, 0xa2, 0xcc, 0x84, 0x46, 0x9e, 0x15, 0x4d, 0xc3, 0xb0, 0xd4, 0x42, 0x35, 0x54, 0xee, 0x27,
	0x42, 0xaf, 0x2d, 0x3b, 0x2e, 0x97, 0xa7, 0x26, 0xd9, 0x43, 0x7a, 0x50, 0xb5, 0x5a, 0x64, 0x42,
	0xa6, 0xc3, 0xf9, 0x6d, 0x6f, 0x87, 0x59, 0xef, 0xb9, 0x16, 0x2a, 0x30, 0x23, 0xcc, 0xa1, 0x43,
	0x04, 0xe4, 0x69, 0x68, 0x20, 0x6b, 0x6f, 0x42, 0xa6, 0x83, 0x80, 0x9a, 0xd2, 0xb2, 0xaa, 0xb0,
	0x15, 0x3d, 0x38, 0xe2, 0x6b, 0x6d, 0xed, 0x4f, 0xf6, 0xa7, 0xc3, 0xf9, 0x9d, 0x9d, 0xdc, 0x5d,
	0x8d, 0x2b, 0xbe, 0x0e, 0xcc, 0xb4, 0xfb, 0x82, 0x5e, 0x3a, 0x03, 0x30, 0xaf, 0x22, 0x46, 0xd1,
	0x88, 0xb6, 0xbd, 0x3a, 0x0d, 0xaf, 0x4d, 0xc3, 0x7b, 0xd6, 0xa6, 0x11, 0x98, 0x3e, 0x76, 0x95,
	0x0e, 0xba, 0x1a, 0xeb, 0x83, 0xfb, 0x92, 0xde, 0x3c, 0x94, 0x1a, 0x7b, 0x92, 0xd1, 0x81, 0x78,
	0x57, 0x0a, 0x8d, 0x6c, 0x4e, 0xeb, 0x30, 0x1b, 0x9b, 0xd5, 0xce, 0xc1, 0xe2, 0xca, 0xe6, 0xbb,
	0x73, 0xf1, 0xf2, 0xef, 0xf6, 0x23, 0x96, 0x08, 0xa8, 0xe9, 0x32, 0xce, 0xdd, 0x8f, 0x84, 0xde,
	0xda, 0xce, 0xad, 0x0b, 0xc8, 0xb5, 0x60, 0x25, 0xbd, 0xde, 0x7b, 0xff, 0x2c, 0x62, 0x72, 0x7b,
	0xf0, 0x5f, 0xb9, 0x75, 0xb6, 0x04, 0x56, 0xdc, 0xb3, 0x7e, 0xfe, 0x8b, 0xd0, 0x71, 0xcf, 0xd4,
	0x53, 0xa1, 0x8e, 0x65, 0x2c, 0xd8, 0x17, 0x42, 0x47, 0xdb, 0x2c, 0xb0, 0xd5, 0x4e, 0x5d, 0xff,
	0x90, 0xae, 0xfd, 0xf8, 0x9c, 0x2c, 0x75, 0x8e, 0xae, 0xfb, 0xfe, 0xdb, 0xcf, 0x0f, 0x7b, 0x23,
	0x66, 0xfb, 0xbd, 0x71, 0x2e, 0x16, 0x9f, 0x37, 0x63, 0xf2, 0x75, 0x33, 0x26, 0x3f, 0x36, 0x63,
	0xf2, 0xea, 0x5e, 0xe7, 0xd5, 0x3e, 0x39, 0x95, 0x70, 0xc8, 0x23, 0xbf, 0x56, 0x30, 0x6b, 0x15,
	0x54, 0x0f, 0xf4, 0x11, 0x2f, 0x64, 0x58, 0x44, 0xd1, 0x05, 0x73, 0xc7, 0xee, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0xa8, 0xa9, 0xc9, 0x36, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContributionConllectionServiceClient is the client API for ContributionConllectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContributionConllectionServiceClient interface {
	ListContributionConllections(ctx context.Context, in *ListContributionConllectionsRequest, opts ...grpc.CallOption) (*ListContributionConllectionsResponse, error)
}

type contributionConllectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewContributionConllectionServiceClient(cc *grpc.ClientConn) ContributionConllectionServiceClient {
	return &contributionConllectionServiceClient{cc}
}

func (c *contributionConllectionServiceClient) ListContributionConllections(ctx context.Context, in *ListContributionConllectionsRequest, opts ...grpc.CallOption) (*ListContributionConllectionsResponse, error) {
	out := new(ListContributionConllectionsResponse)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.ContributionConllectionService/ListContributionConllections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContributionConllectionServiceServer is the server API for ContributionConllectionService service.
type ContributionConllectionServiceServer interface {
	ListContributionConllections(context.Context, *ListContributionConllectionsRequest) (*ListContributionConllectionsResponse, error)
}

func RegisterContributionConllectionServiceServer(s *grpc.Server, srv ContributionConllectionServiceServer) {
	s.RegisterService(&_ContributionConllectionService_serviceDesc, srv)
}

func _ContributionConllectionService_ListContributionConllections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContributionConllectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContributionConllectionServiceServer).ListContributionConllections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.ContributionConllectionService/ListContributionConllections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContributionConllectionServiceServer).ListContributionConllections(ctx, req.(*ListContributionConllectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContributionConllectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "programming_lab.prolab_accounts.ContributionConllectionService",
	HandlerType: (*ContributionConllectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContributionConllections",
			Handler:    _ContributionConllectionService_ListContributionConllections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contribution_conllections.proto",
}

func (m *ContributionConllection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContributionConllection) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.User != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContributionConllections(dAtA, i, uint64(m.User.Size()))
		n1, err := m.User.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.TotalCount != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintContributionConllections(dAtA, i, uint64(m.TotalCount))
	}
	if len(m.Days) > 0 {
		for _, msg := range m.Days {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintContributionConllections(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ContributionDay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContributionDay) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Date != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContributionConllections(dAtA, i, uint64(m.Date.Size()))
		n2, err := m.Date.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Count != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintContributionConllections(dAtA, i, uint64(m.Count))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListContributionConllectionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListContributionConllectionsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.UsersCount != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintContributionConllections(dAtA, i, uint64(m.UsersCount))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListContributionConllectionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListContributionConllectionsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContributionConllections) > 0 {
		for _, msg := range m.ContributionConllections {
			dAtA[i] = 0xa
			i++
			i = encodeVarintContributionConllections(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintContributionConllections(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ContributionConllection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovContributionConllections(uint64(l))
	}
	if m.TotalCount != 0 {
		n += 1 + sovContributionConllections(uint64(m.TotalCount))
	}
	if len(m.Days) > 0 {
		for _, e := range m.Days {
			l = e.Size()
			n += 1 + l + sovContributionConllections(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContributionDay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Date != nil {
		l = m.Date.Size()
		n += 1 + l + sovContributionConllections(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovContributionConllections(uint64(m.Count))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListContributionConllectionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UsersCount != 0 {
		n += 1 + sovContributionConllections(uint64(m.UsersCount))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListContributionConllectionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ContributionConllections) > 0 {
		for _, e := range m.ContributionConllections {
			l = e.Size()
			n += 1 + l + sovContributionConllections(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovContributionConllections(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozContributionConllections(x uint64) (n int) {
	return sovContributionConllections(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContributionConllection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContributionConllections
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContributionConllection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContributionConllection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContributionConllections
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &User{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCount", wireType)
			}
			m.TotalCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Days", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContributionConllections
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Days = append(m.Days, &ContributionDay{})
			if err := m.Days[len(m.Days)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContributionConllections(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContributionDay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContributionConllections
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContributionDay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContributionDay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContributionConllections
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Date == nil {
				m.Date = &types.Timestamp{}
			}
			if err := m.Date.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContributionConllections(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListContributionConllectionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContributionConllections
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListContributionConllectionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListContributionConllectionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsersCount", wireType)
			}
			m.UsersCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UsersCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContributionConllections(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListContributionConllectionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContributionConllections
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListContributionConllectionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListContributionConllectionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionConllections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContributionConllections
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributionConllections = append(m.ContributionConllections, &ContributionConllection{})
			if err := m.ContributionConllections[len(m.ContributionConllections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContributionConllections(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthContributionConllections
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContributionConllections(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContributionConllections
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContributionConllections
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContributionConllections
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthContributionConllections
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowContributionConllections
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipContributionConllections(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthContributionConllections
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthContributionConllections = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContributionConllections   = fmt.Errorf("proto: integer overflow")
)
