// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roles.proto

package api_pb // import "github.com/ProgrammingLab/prolab-accounts/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role struct {
	RoleId               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_ea2a737e3b5a5bae, []int{0}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListRolesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRolesRequest) Reset()         { *m = ListRolesRequest{} }
func (m *ListRolesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRolesRequest) ProtoMessage()    {}
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_ea2a737e3b5a5bae, []int{1}
}
func (m *ListRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRolesRequest.Unmarshal(m, b)
}
func (m *ListRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRolesRequest.Marshal(b, m, deterministic)
}
func (dst *ListRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRolesRequest.Merge(dst, src)
}
func (m *ListRolesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRolesRequest.Size(m)
}
func (m *ListRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRolesRequest proto.InternalMessageInfo

type ListRolesResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRolesResponse) Reset()         { *m = ListRolesResponse{} }
func (m *ListRolesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRolesResponse) ProtoMessage()    {}
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_ea2a737e3b5a5bae, []int{2}
}
func (m *ListRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRolesResponse.Unmarshal(m, b)
}
func (m *ListRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRolesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRolesResponse.Merge(dst, src)
}
func (m *ListRolesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRolesResponse.Size(m)
}
func (m *ListRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRolesResponse proto.InternalMessageInfo

func (m *ListRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetRoleRequest struct {
	RoleId               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleRequest) Reset()         { *m = GetRoleRequest{} }
func (m *GetRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleRequest) ProtoMessage()    {}
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_ea2a737e3b5a5bae, []int{3}
}
func (m *GetRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleRequest.Unmarshal(m, b)
}
func (m *GetRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleRequest.Marshal(b, m, deterministic)
}
func (dst *GetRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleRequest.Merge(dst, src)
}
func (m *GetRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleRequest.Size(m)
}
func (m *GetRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleRequest proto.InternalMessageInfo

func (m *GetRoleRequest) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*Role)(nil), "programming_lab.prolab_accounts.Role")
	proto.RegisterType((*ListRolesRequest)(nil), "programming_lab.prolab_accounts.ListRolesRequest")
	proto.RegisterType((*ListRolesResponse)(nil), "programming_lab.prolab_accounts.ListRolesResponse")
	proto.RegisterType((*GetRoleRequest)(nil), "programming_lab.prolab_accounts.GetRoleRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoleServiceClient interface {
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*Role, error)
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.RoleService/ListRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.RoleService/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
type RoleServiceServer interface {
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*Role, error)
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

func _RoleService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.RoleService/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.RoleService/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "programming_lab.prolab_accounts.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoles",
			Handler:    _RoleService_ListRoles_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _RoleService_GetRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roles.proto",
}

func init() { proto.RegisterFile("roles.proto", fileDescriptor_roles_ea2a737e3b5a5bae) }

var fileDescriptor_roles_ea2a737e3b5a5bae = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x26, 0xbd, 0xbd, 0xed, 0xed, 0x94, 0x5b, 0xea, 0xd9, 0x18, 0xa2, 0x60, 0x09, 0x08, 0x75,
	0x61, 0x06, 0x5b, 0x71, 0xd3, 0x9d, 0x1b, 0x11, 0xba, 0x28, 0x71, 0xe7, 0x26, 0xcc, 0xa4, 0x63,
	0x1c, 0x48, 0x66, 0xc6, 0xcc, 0x44, 0x90, 0xe2, 0xa6, 0x2f, 0xe0, 0xc2, 0x47, 0xf3, 0x15, 0x7c,
	0x10, 0x99, 0x49, 0xfc, 0x05, 0xa9, 0xee, 0xe6, 0x9c, 0x33, 0xdf, 0xdf, 0xe1, 0xa0, 0x7e, 0x29,
	0x73, 0xa6, 0x23, 0x55, 0x4a, 0x23, 0x61, 0x4f, 0x95, 0x32, 0x2b, 0x49, 0x51, 0x70, 0x91, 0x25,
	0x39, 0xa1, 0xb6, 0x9d, 0x13, 0x9a, 0x90, 0x34, 0x95, 0x95, 0x30, 0x3a, 0xd8, 0xcd, 0xa4, 0xcc,
	0x72, 0x86, 0x89, 0xe2, 0x98, 0x08, 0x21, 0x0d, 0x31, 0x5c, 0x8a, 0x06, 0x1e, 0xec, 0x34, 0x53,
	0x57, 0xd1, 0xea, 0x0a, 0xb3, 0x42, 0x99, 0xbb, 0x7a, 0x18, 0x4e, 0x51, 0x3b, 0x96, 0x39, 0x83,
	0x6d, 0xd4, 0xb5, 0x92, 0x09, 0x5f, 0xfa, 0xde, 0xc8, 0x1b, 0xff, 0x8f, 0x3b, 0xb6, 0x3c, 0x5f,
	0x02, 0xa0, 0xb6, 0x20, 0x05, 0xf3, 0x5b, 0x23, 0x6f, 0xdc, 0x8b, 0xdd, 0x3b, 0x04, 0x34, 0x9c,
	0x73, 0x6d, 0x2c, 0x50, 0xc7, 0xec, 0xa6, 0x62, 0xda, 0x84, 0x0b, 0xb4, 0xf5, 0xa1, 0xa7, 0x95,
	0x14, 0x9a, 0xc1, 0x0c, 0xfd, 0x75, 0x41, 0x7c, 0x6f, 0xf4, 0x67, 0xdc, 0x9f, 0xec, 0x47, 0x1b,
	0x92, 0x44, 0x16, 0x1e, 0xd7, 0x98, 0xf0, 0x00, 0x0d, 0xce, 0x98, 0x23, 0x6c, 0x34, 0xbe, 0x35,
	0x39, 0x79, 0x68, 0xa1, 0xbe, 0xfd, 0x78, 0xc1, 0xca, 0x5b, 0x9e, 0x32, 0x58, 0x7b, 0xa8, 0xf7,
	0xe6, 0x06, 0x8e, 0x36, 0xca, 0x7e, 0x4d, 0x13, 0x4c, 0x7e, 0x03, 0xa9, 0xc3, 0x86, 0x83, 0xf5,
	0xd3, 0xf3, 0x63, 0xeb, 0x1f, 0x74, 0xb0, 0xf3, 0x0f, 0x2b, 0xd4, 0x6d, 0xfc, 0x03, 0xde, 0x48,
	0xf7, 0x39, 0x69, 0xf0, 0xb3, 0x4d, 0x85, 0xbe, 0x93, 0x04, 0x18, 0xd6, 0x92, 0x78, 0xd5, 0xac,
	0xe7, 0xfe, 0xf4, 0xe4, 0xf2, 0x38, 0xe3, 0xe6, 0xba, 0xa2, 0x51, 0x2a, 0x0b, 0xbc, 0x78, 0x27,
	0x9b, 0x13, 0x8a, 0x6b, 0xae, 0xc3, 0x57, 0x2e, 0x7b, 0x37, 0x33, 0xa2, 0x78, 0xa2, 0x28, 0xed,
	0xb8, 0xb3, 0x98, 0xbe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x85, 0x8c, 0xfc, 0xcf, 0x81, 0x02, 0x00,
	0x00,
}
