// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_blogs.proto

package api_pb // import "github.com/ProgrammingLab/prolab-accounts/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blog struct {
	BlogId               uint32   `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	FeedUrl              string   `protobuf:"bytes,3,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_blogs_017a6ac4ff8d807f, []int{0}
}
func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (dst *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(dst, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetBlogId() uint32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *Blog) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Blog) GetFeedUrl() string {
	if m != nil {
		return m.FeedUrl
	}
	return ""
}

type CreateUserBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	AutoDetectFeed       bool     `protobuf:"varint,2,opt,name=auto_detect_feed,json=autoDetectFeed,proto3" json:"auto_detect_feed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserBlogRequest) Reset()         { *m = CreateUserBlogRequest{} }
func (m *CreateUserBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserBlogRequest) ProtoMessage()    {}
func (*CreateUserBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_blogs_017a6ac4ff8d807f, []int{1}
}
func (m *CreateUserBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserBlogRequest.Unmarshal(m, b)
}
func (m *CreateUserBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserBlogRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserBlogRequest.Merge(dst, src)
}
func (m *CreateUserBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserBlogRequest.Size(m)
}
func (m *CreateUserBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserBlogRequest proto.InternalMessageInfo

func (m *CreateUserBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func (m *CreateUserBlogRequest) GetAutoDetectFeed() bool {
	if m != nil {
		return m.AutoDetectFeed
	}
	return false
}

type UpdateUserBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	AutoDetectFeed       bool     `protobuf:"varint,2,opt,name=auto_detect_feed,json=autoDetectFeed,proto3" json:"auto_detect_feed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserBlogRequest) Reset()         { *m = UpdateUserBlogRequest{} }
func (m *UpdateUserBlogRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserBlogRequest) ProtoMessage()    {}
func (*UpdateUserBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_blogs_017a6ac4ff8d807f, []int{2}
}
func (m *UpdateUserBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserBlogRequest.Unmarshal(m, b)
}
func (m *UpdateUserBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserBlogRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserBlogRequest.Merge(dst, src)
}
func (m *UpdateUserBlogRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserBlogRequest.Size(m)
}
func (m *UpdateUserBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserBlogRequest proto.InternalMessageInfo

func (m *UpdateUserBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func (m *UpdateUserBlogRequest) GetAutoDetectFeed() bool {
	if m != nil {
		return m.AutoDetectFeed
	}
	return false
}

type DeleteUserBlogRequest struct {
	BlogId               uint32   `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserBlogRequest) Reset()         { *m = DeleteUserBlogRequest{} }
func (m *DeleteUserBlogRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserBlogRequest) ProtoMessage()    {}
func (*DeleteUserBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_blogs_017a6ac4ff8d807f, []int{3}
}
func (m *DeleteUserBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserBlogRequest.Unmarshal(m, b)
}
func (m *DeleteUserBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserBlogRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserBlogRequest.Merge(dst, src)
}
func (m *DeleteUserBlogRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserBlogRequest.Size(m)
}
func (m *DeleteUserBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserBlogRequest proto.InternalMessageInfo

func (m *DeleteUserBlogRequest) GetBlogId() uint32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func init() {
	proto.RegisterType((*Blog)(nil), "programming_lab.prolab_accounts.Blog")
	proto.RegisterType((*CreateUserBlogRequest)(nil), "programming_lab.prolab_accounts.CreateUserBlogRequest")
	proto.RegisterType((*UpdateUserBlogRequest)(nil), "programming_lab.prolab_accounts.UpdateUserBlogRequest")
	proto.RegisterType((*DeleteUserBlogRequest)(nil), "programming_lab.prolab_accounts.DeleteUserBlogRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserBlogServiceClient is the client API for UserBlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserBlogServiceClient interface {
	CreateUserBlog(ctx context.Context, in *CreateUserBlogRequest, opts ...grpc.CallOption) (*Blog, error)
	UpdateUserBlog(ctx context.Context, in *UpdateUserBlogRequest, opts ...grpc.CallOption) (*Blog, error)
	DeleteUserBlog(ctx context.Context, in *DeleteUserBlogRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userBlogServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserBlogServiceClient(cc *grpc.ClientConn) UserBlogServiceClient {
	return &userBlogServiceClient{cc}
}

func (c *userBlogServiceClient) CreateUserBlog(ctx context.Context, in *CreateUserBlogRequest, opts ...grpc.CallOption) (*Blog, error) {
	out := new(Blog)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.UserBlogService/CreateUserBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBlogServiceClient) UpdateUserBlog(ctx context.Context, in *UpdateUserBlogRequest, opts ...grpc.CallOption) (*Blog, error) {
	out := new(Blog)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.UserBlogService/UpdateUserBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBlogServiceClient) DeleteUserBlog(ctx context.Context, in *DeleteUserBlogRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/programming_lab.prolab_accounts.UserBlogService/DeleteUserBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserBlogServiceServer is the server API for UserBlogService service.
type UserBlogServiceServer interface {
	CreateUserBlog(context.Context, *CreateUserBlogRequest) (*Blog, error)
	UpdateUserBlog(context.Context, *UpdateUserBlogRequest) (*Blog, error)
	DeleteUserBlog(context.Context, *DeleteUserBlogRequest) (*empty.Empty, error)
}

func RegisterUserBlogServiceServer(s *grpc.Server, srv UserBlogServiceServer) {
	s.RegisterService(&_UserBlogService_serviceDesc, srv)
}

func _UserBlogService_CreateUserBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBlogServiceServer).CreateUserBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.UserBlogService/CreateUserBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBlogServiceServer).CreateUserBlog(ctx, req.(*CreateUserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBlogService_UpdateUserBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBlogServiceServer).UpdateUserBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.UserBlogService/UpdateUserBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBlogServiceServer).UpdateUserBlog(ctx, req.(*UpdateUserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBlogService_DeleteUserBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBlogServiceServer).DeleteUserBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/programming_lab.prolab_accounts.UserBlogService/DeleteUserBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBlogServiceServer).DeleteUserBlog(ctx, req.(*DeleteUserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserBlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "programming_lab.prolab_accounts.UserBlogService",
	HandlerType: (*UserBlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserBlog",
			Handler:    _UserBlogService_CreateUserBlog_Handler,
		},
		{
			MethodName: "UpdateUserBlog",
			Handler:    _UserBlogService_UpdateUserBlog_Handler,
		},
		{
			MethodName: "DeleteUserBlog",
			Handler:    _UserBlogService_DeleteUserBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_blogs.proto",
}

func init() { proto.RegisterFile("user_blogs.proto", fileDescriptor_user_blogs_017a6ac4ff8d807f) }

var fileDescriptor_user_blogs_017a6ac4ff8d807f = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x86, 0x49, 0xb7, 0xb4, 0x75, 0x8a, 0x31, 0x0c, 0x6c, 0x5b, 0xa3, 0xd2, 0x12, 0x28, 0x2c,
	0x05, 0x67, 0x64, 0x95, 0x82, 0x7a, 0x57, 0xab, 0x20, 0xf4, 0x42, 0x22, 0x7b, 0xe3, 0xcd, 0x30,
	0x93, 0x9c, 0x8d, 0x81, 0x49, 0x26, 0x4e, 0x26, 0x82, 0xa8, 0x08, 0xde, 0xf8, 0x00, 0x82, 0x6f,
	0xe2, 0x93, 0xf8, 0x0a, 0x3e, 0x88, 0x9c, 0xd9, 0x5d, 0x74, 0xd9, 0x95, 0xcd, 0x5d, 0xaf, 0x92,
	0xf9, 0x27, 0xe7, 0xfc, 0xdf, 0xfc, 0x99, 0x43, 0xa2, 0xae, 0x05, 0x2b, 0x94, 0x36, 0x45, 0xcb,
	0x1a, 0x6b, 0x9c, 0xa1, 0xc7, 0x8d, 0x35, 0x85, 0x95, 0x55, 0x55, 0xd6, 0x85, 0xd0, 0x52, 0xa1,
	0xac, 0xa5, 0x12, 0x32, 0xcb, 0x4c, 0x57, 0xbb, 0x36, 0xbe, 0x5b, 0x18, 0x53, 0x68, 0xe0, 0xb2,
	0x29, 0xb9, 0xac, 0x6b, 0xe3, 0xa4, 0x2b, 0x4d, 0x3d, 0x2f, 0x8f, 0xef, 0xcc, 0x77, 0xfd, 0x4a,
	0x75, 0x53, 0x0e, 0x55, 0xe3, 0x3e, 0xcc, 0x36, 0x93, 0x2b, 0xb2, 0x7d, 0xa1, 0x4d, 0x41, 0x0f,
	0xc9, 0x2e, 0x5a, 0x8a, 0x32, 0x3f, 0x0a, 0x4e, 0x82, 0xd1, 0xcd, 0x74, 0x07, 0x97, 0x2f, 0x73,
	0x1a, 0x91, 0x41, 0x67, 0xf5, 0xd1, 0xd6, 0x49, 0x30, 0xba, 0x91, 0xe2, 0x2b, 0xbd, 0x4d, 0xf6,
	0xa6, 0x00, 0xb9, 0x40, 0x79, 0xe0, 0xe5, 0x5d, 0x5c, 0x4f, 0xac, 0x4e, 0x3e, 0x91, 0xe1, 0x33,
	0x0b, 0xd2, 0xc1, 0xa4, 0x05, 0x8b, 0x7d, 0x53, 0x78, 0xd7, 0x41, 0xeb, 0xe8, 0x63, 0xb2, 0x8d,
	0xfd, 0x7c, 0xef, 0xfd, 0xf1, 0x29, 0xdb, 0x70, 0x22, 0xe6, 0x6b, 0x7d, 0x09, 0x1d, 0x91, 0x48,
	0x76, 0xce, 0x88, 0x1c, 0x1c, 0x64, 0x4e, 0xa0, 0x95, 0xa7, 0xd9, 0x4b, 0x43, 0xd4, 0x2f, 0xbd,
	0xfc, 0x02, 0x20, 0x47, 0xf7, 0x49, 0x93, 0x5f, 0x97, 0xfb, 0x03, 0x32, 0xbc, 0x04, 0x0d, 0xab,
	0xee, 0xff, 0x8b, 0x76, 0xfc, 0x73, 0x40, 0x6e, 0x2d, 0x3e, 0x7e, 0x0d, 0xf6, 0x7d, 0x99, 0x01,
	0xfd, 0x16, 0x90, 0x70, 0x39, 0x42, 0x7a, 0xbe, 0x91, 0x77, 0x6d, 0xe6, 0x71, 0xbf, 0x73, 0x26,
	0x07, 0x5f, 0x7f, 0xfd, 0xfe, 0xbe, 0x15, 0x25, 0xfb, 0x1c, 0x2f, 0x1e, 0xf7, 0x17, 0xef, 0x49,
	0x70, 0x46, 0x7f, 0x04, 0x24, 0x5c, 0x8e, 0xb3, 0x07, 0xc9, 0xda, 0xfc, 0xfb, 0x92, 0x9c, 0x7a,
	0x92, 0xe3, 0x71, 0xfc, 0x0f, 0x09, 0xff, 0x88, 0x0f, 0x36, 0x0f, 0xf0, 0x33, 0x82, 0x7d, 0x21,
	0xe1, 0x72, 0xd0, 0x3d, 0xb8, 0xd6, 0xfe, 0x99, 0xf8, 0x80, 0xcd, 0x46, 0x83, 0x2d, 0x46, 0x83,
	0x3d, 0xc7, 0xd1, 0x48, 0xee, 0x79, 0x90, 0xc3, 0xb3, 0xe1, 0x0a, 0x08, 0x32, 0x5c, 0x9c, 0xbf,
	0x79, 0x54, 0x94, 0xee, 0x6d, 0xa7, 0x58, 0x66, 0x2a, 0xfe, 0xea, 0xaf, 0xf5, 0x95, 0x54, 0x7c,
	0xe6, 0x7c, 0x7f, 0xe1, 0x8c, 0x33, 0xf9, 0x54, 0x36, 0xa5, 0x68, 0x94, 0xda, 0xf1, 0x36, 0x0f,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x0d, 0xe4, 0xbf, 0xe2, 0x03, 0x00, 0x00,
}
